version: '3.0'

services:

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    depends_on:
      - redis

  web:
    build: .
    tty: true
    restart: always
    volumes:
      - .:/code
    env_file:
      - .docker.env
    command: bash -c 'alembic upgrade head && uvicorn main:app --host 0.0.0.0 --reload'
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  pg_data:
