"""empty message

Revision ID: 17736801c2cd
Revises: 28e58b6ccd00
Create Date: 2024-01-19 23:45:13.021070

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = '17736801c2cd'
down_revision: str | None = '28e58b6ccd00'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
