"""init

Revision ID: 48562e213a7e
Revises:
Create Date: 2024-01-18 18:50:39.096596

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = '48562e213a7e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
