"""empty message

Revision ID: 67cdedb90c1b
Revises: c3ecbdd382f2
Create Date: 2024-01-18 21:09:23.302783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67cdedb90c1b'
down_revision: Union[str, None] = 'c3ecbdd382f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('submenu_id', sa.Integer(), nullable=False))
    op.drop_constraint('dish_sub_menu_id_fkey', 'dish', type_='foreignkey')
    op.create_foreign_key(None, 'dish', 'submenu', ['submenu_id'], ['id'], ondelete='CASCADE')
    op.drop_column('dish', 'sub_menu_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('sub_menu_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.create_foreign_key('dish_sub_menu_id_fkey', 'dish', 'submenu', ['sub_menu_id'], ['id'], ondelete='CASCADE')
    op.drop_column('dish', 'submenu_id')
    # ### end Alembic commands ###
