"""empty message

Revision ID: c95ebf42e676
Revises: be4ce9e10214
Create Date: 2024-01-19 22:34:04.713269

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c95ebf42e676'
down_revision: str | None = 'be4ce9e10214'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
